config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/sdaas:
      branch: master
      repo: https://github.com/rizac/sdaas.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/sdaas git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-scarlet-camel.sh
        container: qc.acc_grumpy-amaranth-sparrow
  QC.Doc:
    repos:
      github.com/rizac/sdaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-platinum-chipmunk.sh
        container: qc.doc_goopy-tangerine-numbat
      github.com/rizac/sdaas git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orange-mandrill.sh
        container: qc.doc_bumpy-myrtle-chicken
      github.com/rizac/sdaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-indigo-loon.sh
        container: qc.doc_smelly-gold-quail
  QC.Lic:
    repos:
      github.com/rizac/sdaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chartreuse-eagle.sh
        container: qc.lic_gummy-emerald-starfish
  QC.Sec:
    repos:
      github.com/rizac/sdaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-razzmatazz-quail.sh
        container: qc.sec_scaly-firebrick-duck
  QC.Sty:
    repos:
      github.com/rizac/sdaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-cerise-anteater.sh
        container: qc.sty_skanky-taupe-lemming
  QC.Uni:
    repos:
      github.com/rizac/sdaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-beige-magpie.sh
        container: qc.uni_shaky-chocolate-collie
  QC.Ver:
    repos:
      github.com/rizac/sdaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-ochre-wildebeest.sh
        container: qc.ver_sloppy-amethyst-bobcat
timeout: 5400
